### ISSUE TITLE
Rebooting should not activate then reboot

### ISSUE THREAD

**Issue by grahamc** [zhaofengli/colmena#113]
#46 was closed by 1be16d552d99c772b0bbf7e98b541244f618206d which added a --reboot flag which activates the new config, then issues the reboot. I believe it would be better to reboot and not activate at all. Then, once it is up, upload keys.

In my case I have software whose userland programs bind closely to an API in the kernel module. If these two get out of sync, it could cause problems. This could be troublesome if a new version's activation is run.

**Comment by lheckemann** [comment]
Does `colmena apply --reboot boot` not already do what you want? I suppose the one missing piece is that post-activation key upload should take place after the reboot and not before it.

**Comment by zhaofengli** [comment]
Sorry, I forgot about this issue. Let's make the default goal of `colmena apply` be `boot` if `--reboot` is specified, and move the upload of post-activation keys after the reboot.
