### ISSUE TITLE
Feature request: repl integration

### ISSUE THREAD

**Issue by aanderse** [zhaofengli/colmena#115]
[arion](https://github.com/hercules-ci/arion) has a really nice feature: `nix repl` integration. While `colmena` has `colmena eval -E`, which is good, `colmena repl` would be **amazing**.

The basic idea being that `colmena repl` would drop me into a `nix repl` that has `nodes` (as well as `nixpkgs` and `lib`, or whatever `colmena eval` has) already loaded for me.

**Comment by otavio** [comment]
Indeed. It would be very helpful.

**Comment by aanderse** [comment]
Thanks so much @zhaofengli :tada:

It might be worth noting that this feature requires `nix` version `2.10` or above.

**Comment by zhaofengli** [comment]
Thanks for testing! I [switched](https://github.com/zhaofengli/colmena/commit/741d5c4fbbd6cf273c330baa6c035263e76a1071) it to emit a temporary file with the Nix expression instead so it's compatible with Nix 2.3+.
