### ISSUE TITLE
Key services don't work correctly

### ISSUE THREAD

**Issue by cprussin** [zhaofengli/colmena#116]
~~As far as I can tell, it looks like systemd path units are always active, so binding to them causes bound units to be activated, even when the paths aren't mounted.  In particular, [this line](https://github.com/zhaofengli/colmena/blob/main/src/nix/hive/modules.nix#L81) causes `${name}-key.service` to activate as soon as the machine is up.  The service immediately fails due to [this block](https://github.com/zhaofengli/colmena/blob/main/src/nix/hive/modules.nix#L87-L90), but all the same it being activated is enough to trigger all dependent units.  What this means is that units that depend on keys and are configured to wait for key units before activating are activating as soon as the machine boots, even though the keys aren't present.~~

~~Note that the binding line isn't necessary anyways as path units will automatically activate their related services once the path conditions are met.~~

~~I think we need to remove the `bindsTo` line.  I'll put in a PR.~~

**EDIT:** My understanding of systemd here is limited and I don't really understand what's going on.  In any case, the `path` unit does not appear to work as expected and seems to be getting triggered unintentionally, and sometimes failing with `unit-start-limit-hit`.  I'm struggling to find any docs that can help me understand, but at this point I'll probably put together a fork of colmena that doesn't use systemd path units here.

**Comment by zhaofengli** [comment]
Hmm, is it possible to come up with a minimal example where this happens? I put my secrets in a separate persistent filesystem that has `neededForBoot = true;`, and so far it seems to work fine.

**Comment by cprussin** [comment]
I'm now less convinced there's an issue with colmena here and I'm thinking there's a more general issue with how my systemd is configured.  I haven't yet been able to figure out exactly what's going on or get a minimal repro, so I'll close this PR until I have a better understanding of the underlying problem and can propose a fix.  Sorry to waste your time @zhaofengli .
