### ISSUE TITLE
Add an option to upload the configuration but don't apply it.

### ISSUE THREAD

**Issue by farcaller** [zhaofengli/colmena#128]
The use case would be to run nix-diff between the /run/current-system and whatever colmena output was.

**Comment by justinas** [comment]
Perhaps you're thinking of `push` or `dry-activate` [goals](https://github.com/zhaofengli/colmena/blob/872949504befb9b5540e69f846c6965def7150f9/src/nix/deployment/goal.rs#L5)?

I use `colmena apply -v dry-activate` with an activation script that diffs the closures.

```nix
{
  system.activationScripts.system-diff = {
    supportsDryActivation = true; # safe: only outputs to stdout
    text = ''
      if [ -e /run/current-system ]; then
        PATH=$PATH:${pkgs.nix}/bin ${pkgs.nvd}/bin/nvd diff /run/current-system $systemConfig
      fi
    '';
  };
}
```

**Comment by farcaller** [comment]
I didn't realize there's a `push` in there which does exactly what I need. Thanks!
