### ISSUE TITLE
Question: meta.nixpkgs + config.allowUnfree

### ISSUE THREAD

**Issue by aanderse** [zhaofengli/colmena#13]
Consider the following configuration in `hive.nix`:
```
  meta = {
    nixpkgs = import (builtins.fetchTarball {
      name = "nixos-unstable-2020-12-08";
      url = "https://github.com/nixos/nixpkgs/archive/78dc359abf8217da2499a6da0fcf624b139d7ac3.tar.gz";
      sha256 = "0wgfvkwxj8vvy100dccffb6igbqljvhgyxdk8c9gk4k2zlkygz45";
    }) { config.allowUnfree = true; };
  };
```

Should it be necessary to specify `nixpkgs.config.allowUnfree = true;` in machine configurations?

**Comment by zhaofengli** [comment]
It isn't necessary now with #12, and I think that's the expected behavior. I tested with my overlays, and now it's sufficient to just specify them when initializing Nixpkgs and set `meta.nixpkgs` to the resulting attribute set.

More on the "should" aspect: I think the fix is desirable as the old behavior would cause confusion if people tried to pass an initialized Nixpkgs attribute set with various things configured, especially overlays which would quietly get ignored.

**Comment by aanderse** [comment]
Great! Thanks for the answer. I'm really liking this tool so far :smile:

**Comment by aanderse** [comment]
@zhaofengli I think this is still a problem with `apply-local`.

From my `hive.nix`:
```
{
  meta = {
    nixpkgs = import (builtins.fetchTarball {
      name = "nixos-stable-2020-02-17";
      url = "https://github.com/nixos/nixpkgs/archive/5c53c720ff690ef82a9fe4849e7b70c104e1c82f.tar.gz";
      sha256 = "0gjxfxbfc6maqg48k9ai476s6zkc94p0y3v9yjgwbiy7b38pqfys";
    }) { config.allowUnfree = true; overlays = (import ./overlays.nix); };
  };
...
  local-node =
    { config, pkgs, lib, nodes, ... }:
    {
      hardware.enableAllFirmware = true;
      environment.systemPackages = [
        pkgs.yuzu-mainline # a package that exists in an overlay
      ];
    }
}
```

I get the following errors:

```
[ERROR] error:
[ERROR] Failed assertions:
[ERROR] - the list of hardware.enableAllFirmware contains non-redistributable licensed firmware files.
```
This indicates `config.allowUnfree` isn't being used when I run `apply-local`.

```
[ERROR] Evaluation of entadono failed. Last 3 lines of logs:
[ERROR] error: undefined variable 'yuzu-mainline' at /home/aaron/nixos-colmena/profiles/gaming.nix:14:5
```
This indicates `overlays` aren't being applied when I run `apply-local`.

Is this by design, or should `apply-local` also pickup everything from `meta.nixpkgs`?

**Comment by zhaofengli** [comment]
Hmm, there should be no difference between `apply` and `apply-local` in terms of evaluation, and overlays defined both in `meta.nixpkgs` and in machine configurations should be picked up. Just quickly tried, and I can't replicate this on my end on 082a03344347e3baa29f6f165bfcd942d38a968a in my own configs, which has overlays applied in `meta.nixpkgs`.

Could you confirm that you are using the latest commit? I'll try a minimal configuration in a container in a bit.

**Comment by aanderse** [comment]
Well that is embarrassing... 😄 

I had an older commit if `colmena` on this machine. Sorry for the noise.

I'll take this opportunity to mention again I'm really enjoying this tool. Thanks so much for your work on it!

**Comment by zhaofengli** [comment]
(Oops, missed the reply)

You are welcome, and thanks for confirming!
