### ISSUE TITLE
Using nix-sops with buildOnTarget:true fails to activate

### ISSUE THREAD

**Issue by ibizaman** [zhaofengli/colmena#153]
With nix-sops, when building on the target, running `colmena apply` fails activating with the following error:
```
[ERROR]   stderr) activating the configuration...
[ERROR]   stderr) /nix/store/2hbmmwflqrx7wl3akpxqzxqvx7k07m21-sops-install-secrets-0.0.1/bin/sops-install-secrets: Cannot read keyfile '/home/ME/.config/sops/age/secrets.txt': open /home/ME/.config/sops/age/secrets.txt: no such file or directory
```
This makes sense because the activation happens on the target directly. Indeed, if I `scp` the `secrets.txt` over to the target host, then the `apply` command works.
But I guess copying the secret file over defeats the purpose of encrypting the secrets in the first place.

Is it possible to activate the system without copying the secrets file over? Am I missing something here or is what I am trying to do not possible?

**Comment by winterqt** [comment]
What does your configuration look like? There's something off here, as I use sops-nix just fine with `buildOnTarget`.

**Comment by alexpearce** [comment]
I had the same problem as @ibizaman. My host configuration was referencing `./secrets/secret1.age` and I got this message:

```
[ERROR]   stderr) error: getting status of '/nix/store/rkb8n1wn2c7wwgvscy6fj73iqc2ari49-source/hosts/secrets': No such file or directory
```

This makes sense. My host configuration is defined ina subdirectory `hosts/<hostname>.nix`, and my secrets are in a sibling directory `secrets/`.

I changed the path reference to `../secrets/secret1.age` and the build completed successfully.

**Comment by ibizaman** [comment]
Closing because it's been a long time I don't have this issue anymore.

Also, I was using buildOnTarget because I was deploying to a raspberry pi. But since then I discovered we can cross-compile with colmena like so https://colmena.cli.rs/unstable/examples/multi-arch.html

Thanks for taking the time to answer!

**Comment by szethh** [comment]
I'm running into this issue too.


```nix
# relative path to my secrets sops file
sops.defaultSopsFile = ../../secrets/secrets.yaml;
# path to the keys file on my mac
sops.age.keyFile = "/Users/szeth/.config/sops/age/keys.txt";
sops.secrets.CLOUDFLARED_TOKEN = { };
```
I get this error:
```
[ERROR]   stderr) /nix/store/sd6zilxyib9hm4326wfzs7az5z2xx5sc-sops-install-secrets-0.0.1/bin/sops-install-secrets: cannot read keyfile '/Users/szeth/.config/sops/age/keys.txt': open /Users/szeth/.config/sops/age/keys.txt: no such file or directory
```

Obviously I can either copy my private key or my `~/.config/sops/age/keys.txt` file over to my remote machine, but as said by @ibizaman it defeats the purpose of using secrets.

I could also add the remote host's key to my `.sops.yaml` file so that it can also decrypt the secrets, but then every host could access all secrets. I'd rather have only my laptop be able to do that.

I am using `buildOnTarget` since I am on a mac and deploying to NixOS hosts.

Does anyone know a fix to this problem?

**Comment by szethh** [comment]
managed to get it to work by using `deployment.keys`:
```nix
# this copies over my keys.txt file as a secret
deployment.keys = {
  age = {
    keyFile = "/Users/szeth/.config/sops/age/keys.txt";
  };
};

...

sops.defaultSopsFile = ../../secrets/secrets.yaml;
# we reference it here so sops can decrypt our secrets.yaml
sops.age.keyFile = "${config.deployment.keys.age.destDir}/age";
```
