### ISSUE TITLE
colmena build should create a result symlink, like nix-build etc

### ISSUE THREAD

**Issue by tv42** [zhaofengli/colmena#18]
As I'm finetuning a config, I often want to observe the created results. Right now it seems my choices are to either

1. do a full apply -- which I'm not confident enough to do
2.  run `colmena build -v`, hope to catch a `/nix/store/*-nixos-system-*` path in the verbose log. And that path is not mentioned if there was no change, so sometimes that just leaves me eyeballing for nothing!
3. run `colmena build -v`, catch a `/nix/store/*-colmena-hive` path in the verbose log, `cat` that file, and copy-paste a path referred in there

`nix-build` creates a `result` link by default. Could `colmena build` do the same, please? And please also make the contents immediately explorable, without needing to copy-paste a path name.

**Comment by zhaofengli** [comment]
Ok, if the goal is only to build, the tool will now print out all resulting system profile paths. For result links, there is now a `--keep-result` flag that will make Colmena create links under `.gcroots` in the same directory the Hive configuration is in. This matches the behavior of morph, which I think is a reasonable default.

**Comment by zhaofengli** [comment]
I think the new commits should have addressed this issue.
