### ISSUE TITLE
Feature request: deployment.keys option

### ISSUE THREAD

**Issue by aanderse** [zhaofengli/colmena#2]
This project looks amazing! I love how compatible it is with `nixops`. Do you have any plans to implement `deployment.keys` options like NixOps has?

**Comment by zhaofengli** [comment]
Thanks! And yes, it's one of the features that I'm planning to implement before the first "stable" release.

**Comment by aanderse** [comment]
Wonderful! Thank you.

**Comment by aanderse** [comment]
:tada:
