### ISSUE TITLE
Reading environment variables

### ISSUE THREAD

**Issue by alexandre-dos-reis** [zhaofengli/colmena#231]
I would like to provide the `targetHost` value through an env var using `builtins.getEnv "IP"` but it isn't working, the string is empty. Tough, it's working througth `colmena repl`. I'm using a flake.

What I've tried:
```bash
export IP=192.168.1.1
colmena apply
IP=192.168.1.1 colmena apply
```

The error :

```sh
ssh: Could not resolve hostname : No address associated with hostname
error: failed to start SSH connection to 'alex@'

```

My flake config:

```nix
{
  colmena = {
    meta = {...};
    my-node = {
      imports = {...};
      deployment = {
        targetUser = "alex"';
        targetHost = builtins.getEnv "IP";
      }
    }
  }
}
```
What is working:
```bash
❯ IP=51.210.151.4 colmena repl
Welcome to Nix 2.20.5. Type :? for help.

Loading installable ''...
Added 3 variables.
nix-repl> builtins.getEnv "IP"
"51.210.151.4"
```

Is this not working because nix evaluate in a sandbox environment ?

**Comment by itslychee** [comment]
why not just use DNS?

**Comment by justinas** [comment]
> Is this not working because nix evaluate in a sandbox environment ?

Probably, yeah. `nix repl` is not pure-eval by default. Flakes do pure-eval by default. Try `colmena apply --impure`.

**Comment by alexandre-dos-reis** [comment]
Closing because this is related to Nix. Nix consider `builtins.getEnv` to be **impure**.

**Comment by alexandre-dos-reis** [comment]
> why not just use DNS?

Yes I finally adopted this solution but this adds a depencency.
