### ISSUE TITLE
deployment.keys.*.mode documented but not implemented

### ISSUE THREAD

**Issue by tv42** [zhaofengli/colmena#24]
README says https://github.com/zhaofengli/colmena/blame/main/README.md#L206 `mode = "0640";         # Default: 0600` but there's no instance of `mode` in the source code and trying to set it gives error

```
[INFO ] Enumerating nodes...
error: The option `deployment.keys.foo.key.mode' defined in `<unknown-file>' does not exist.
(use '--show-trace' to show detailed location information)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NixFailure { exit_code: 1 }', src/command/apply.rs:122:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by tv42** [comment]
For what it's worth, this makes `group` pointless; the group will never be able to read the file.

**Comment by zhaofengli** [comment]
Well, this is yet another typo that needed to be fixed. The option is called `permissions` to be consistent with NixOps. Thanks for the report!
