### ISSUE TITLE
`system.checks` fail with `buildOnTarget`

### ISSUE THREAD

**Issue by jekor** [zhaofengli/colmena#246]
System checks (both for sshd and varnish in my testing) fail to run when building on target. A symptom is that they appear to try to build via `ssh://localhost` on the target machine. This appears to stall out (because the SSH key is not forwarded to the target?). I can work around the problem at the cost of losing build-time validation by setting:

```
system.checks = lib.mkForce [];
```

**Comment by zhaofengli** [comment]
There should be no difference between the checks and other derivations. Could you give a small example of a check that you are using?

**Comment by jekor** [comment]
Sure, the checks are the ones from the NixOS modules:

- https://github.com/NixOS/nixpkgs/blob/nixos-24.05/nixos/modules/services/networking/ssh/sshd.nix#L683
- https://github.com/NixOS/nixpkgs/blob/nixos-24.05/nixos/modules/services/web-servers/varnish/default.nix#L96

The varnish check appears to be a simple `runCommand`.

More background: When deploying and building on a Linux machine *without* `buildOnTarget`, the checks run fine. When deploying from either a Linux or Darwin machine *with* `buildOnTarget`, the checks fail with the same error. On the Linux machine I have no remote builders configured.

**Comment by jekor** [comment]
I've since realized that the machine I'm noticing this on is running hydra and has a localhost builder. I'm unsure why it works for hydra builds on the machine but not for colmena with buildOnTarget, but it's unlikely to be a problem with colmena.

**Comment by jekor** [comment]
Of note though is that the buildMachine definition uses `protocol = null` (not SSH), so perhaps something (colmena or otherwise) is assuming ssh for remote builders?
