### ISSUE TITLE
How do I ~~pass flake `specialArgs` or generally~~ use an existing `nixosConfiguration` from a flake as a node?

### ISSUE THREAD

**Issue by con-f-use** [zhaofengli/colmena#257]
How do I ~pass flake `specialArgs` or generally~ use an existing `nixosConfiguration` from a flake as a node? If I switch from a `nixos-rebuild --target-host ...` based deployment model to colmena, there's not migration path that doesn't involve a major refactor, it seems.

E.g.:
```nix
outputs = inputs: {
  nixosConfigurations.myConfig = inputs.nixpkgs.lib.nixosSystem { 
    secialArgs = ...; 
    # ...more... 
  };
  colmena = {
    myNode = {
      imports = [ inputs.self.nixosConfigurations.myConfig ];
    };
    # or:
    myOtherNode = inputs.self.nixosConfigurations.myConfig;
  };
}
```
Neither really works, because with `myOtherNode`, the result is not an importable nixos module and colmena errors out ~and with `myNode` there's no way do pass `specialArgs` that I'm aware of~.

Edit: I found https://colmena.cli.rs/unstable/reference/meta.html#specialargs in the mean time. The other point stands, how do I use a `nixosConfiguration` flake output for a colmena node, or wrap it to be one?

**Comment by 1sixth** [comment]
See https://github.com/zhaofengli/colmena/issues/60

**Comment by jtremesay** [comment]
I have read #60, and I have still no idea what I'm supposed to do. someone could be kind enough to provide a complete example for people that have no idea what they are doing?
