### ISSUE TITLE
Using the incorrect value for `meta.nixpkgs` can be fatal

### ISSUE THREAD

**Issue by uhthomas** [zhaofengli/colmena#29]
Hi.

I was in the process of pinning nixpkgs for my cluster of NixOS nodes and ran into an issue where they all downgraded to NixOS `20.03post-git (Markhor)`, along with have really outdated packaged. I couldn't figure out what had gone wrong as `niv` was reporting the correct version of nixpkgs.

The offending line:

```diff nix
- meta.nixpkgs = import (import ./sources.nix).nixpkgs;
+ meta.nixpkgs = import (import ./sources.nix).nixpkgs { };
```

I imagine during evaluation there was confusion about what `nixpkgs` actually was, and so it did the "safe" thing of using a stable version.

Is there anything which can be implemented to prevent this from happening?

**Comment by zhaofengli** [comment]
In this case, you [actually pinned](https://github.com/uhthomas/automata/commit/6acf1f309202133d11c11bd0260dd33f708436c5#diff-b9a0014cf6c4615d1c2e8d921dc3db59b4a68b462788d667ed622331660d17cdL20) Nixpkgs to 20.03 (Niv's default Nixpkgs version). `eval.nix` handles Nixpkgs lambdas in `meta.nixpkgs` fine, and it defaults to `<nixpkgs>` which is typically updated with `nix-channel` on your system.

**Comment by uhthomas** [comment]
I am not sure that is the case. The original commit was https://github.com/NixOS/nixpkgs/commit/1db42b7fe3878f3f5f7a4f2dc210772fd080e205 (16 days ago) and the amended commit is https://github.com/NixOS/nixpkgs/commit/1b1faeb2dbbfd138bf42a0c64ed7dbbd336a5831 (today).

**Comment by zhaofengli** [comment]
That's the 20.03 branch.

**Comment by uhthomas** [comment]
Heh, I see.

Thank you very much @zhaofengli and sorry for the confusion. Colmena has been a lot of fun to play with.
