### ISSUE TITLE
Eval stopped when containers.*.config is defined.

### ISSUE THREAD

**Issue by yonghan** [zhaofengli/colmena#37]
I am defining a nixos container that would be deployed to a VPS by `colmena`, however, evaluation stops whenever I have `containers.*.config` defined.

Error message: 
`evaluation failed: nix was killed by signal 9`

No trace available.

**Comment by zhaofengli** [comment]
Your machine likely ran out of memory during evaluation, which you can confirm in `dmesg`. How much RAM does your machine have and how many nodes are there in total in your configuration? You can also try specifying `--eval-node-limit 1` and see if that helps (it overrides the built-in heuristic that determines how many nodes to evaluate at once).

**Comment by yonghan** [comment]
Indeed! Increased VM memory from 1G to 2G and the deployment completed smoothly.
