### ISSUE TITLE
Overlays are applied both from nixpkgs.overlays and from ~/.config/nixpkgs/overlays.nix

### ISSUE THREAD

**Issue by Ekleog** [zhaofengli/colmena#39]
Hello,

In the process of migrating to colmena, I discovered a weirdness around the handling of overlays: when passing nixpkgs by path to colmena (`meta.nixpkgs = ./nixpkgs;`), it imports the `~/.config/nixpkgs/overlays.nix` overlays.

I'd have expected the default arguments to the nixpkgs lambda to be `overlays = [];`, so that the impurity of home-local overlays wouldn't come up.

Would that make sense to you, or do you think the current behavior is the correct one? (In which case I'd think maybe a warning somewhere might be appropriate, as I ended up debugging why my overlay was being applied twice, once from ~/.config and once from nixpkgs.overlays, for 45 minutes today, and only figured it out after having failed to create a reproducer for the issue)

Anyway, a simple workaround is to set `meta.nixpkgs = import ./nixpkgs { overlays = []; };`, which is the way I'm going to go for now, but I'm thinking changing the default might make colmena more accessible to new users that wouldn't expect user-local overlays to be applied to deployments :)

**Comment by dminuoso** [comment]
What is the contents of your nixpkgs.nix file?

**Comment by Ekleog** [comment]
Which nixpkgs.nix file are you speaking of?

**Comment by dminuoso** [comment]
Ah sorry I misread. What you describe is not a colmena bug, but a (mis?)feature of nixpkgs.

The top-level expression of nixpkgs defaults to `./pkgs/top-level/impure.nix`, which has a lot of highly impure default values for the initialization parameters. [See this link](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/impure.nix). That's where the overlays come from.

You can use nixpkgs/pkgs/top-level/default.nix instead which has no impure defaults.

**Comment by Ekleog** [comment]
I know, and I actually listed the workaround in my top post, my point is that colmena should not include user-wide overlays when passing just a path to `meta.nixpkgs` :)

It's probably very easy to fix, and I can most likely submit a PR quickly if I receive confirmation that this is a behavior colmena devs also want to change.

**Comment by dminuoso** [comment]
It’s nixpkgs that includes the overlays, not colmena. At best this is a nixpkgs bug.

It is you who decided to use an impure mix expression.

**Comment by Ekleog** [comment]
Awesome, thank you!
