### ISSUE TITLE
Add support for the 'keyFile' parameter for deployment keys

### ISSUE THREAD

**Issue by justinas** [zhaofengli/colmena#4]
In the spirit of #3. I am very interested in uploading the key from a local path specified by `keyFile` option ([reference code in NixOps](https://github.com/NixOS/nixops/blob/1ed5a091bc52de6c91319f446f833018a1cb326e/nix/keys.nix#L54-L73)).

@zhaofengli  I am very willing to implement this myself in the coming days, so just creating this issue to inquire whether you might already be on this issue - don't want to duplicate effort.

**Comment by zhaofengli** [comment]
Sure, please go ahead!
