### ISSUE TITLE
remote lost configuration (back to clean install)

### ISSUE THREAD

**Issue by yonghan** [zhaofengli/colmena#40]
I am not sure if this is a Colmena specific issue but since I couldn't find anything on the web, so, I am asking it here.

How I install NixOS these days is I boot an empty VPS with the NixOS iso, run nixos-generate-config, uncomment lines to enable GRUB and ssh, allow password on root ssh login, then install. Once rebooted I have a minimal NixOS install with root password set.

Then I use colmena to get the system to the point where I need it to be.

However these few days I noticed that the VPS I deployed using colmena would 'reset' to the initial minimal install I had before colmena. (users gone, services not available, etc). This happens daily. Initially I thought that was because I enabled garbage collection daily, but it still persists after I turned gc off.

As I am new to NixOS, I hope someone would point me where to look if this is not a colmena bug.

**Comment by justinas** [comment]
Do you have anything like [`system.autoUpgrade.enable`](https://search.nixos.org/options?channel=21.05&show=system.autoUpgrade.enable&from=0&size=50&sort=relevance&type=packages&query=autoupgrade) set? It basically does `nixos-rebuild switch --upgrade`, that is, it uses your `/etc/nixos/configuration.nix`, which presumably still contains your early configuration, ant does not include stuff you did in Colmena.

**Comment by yonghan** [comment]
I think what you said make sense. I did have `https://search.nixos.org/options?channel=21.05&show=system.autoUpgrade.enable&from=0&size=50&sort=relevance&type=packages&query=autoupgrade` set indeed.

How do we configure colmena so that the systems auto upgrade themselves using the colmena configuration and not their own configuration.nix?

**Comment by justinas** [comment]
> I think what you said make sense. I did have `system.autoUpgrade.enable` set indeed.
> 
> How do we configure colmena so that the systems auto upgrade themselves using the colmena configuration and not their own configuration.nix?

You'll probably need to roll your own cronjob (or rather, a systemd timer). If you have your config in a git repo, this job might be as simple as `git pull && colmena apply-local`.

You could take some inspiration from the [autoUpgrade](https://github.com/NixOS/nixpkgs/blob/2553aee74fed8c2205a4aeb3ffd206ca14ede60f/nixos/modules/tasks/auto-upgrade.nix) module. It implements some neat functionality for detecting whether the kernel received an upgrade and reboot conditionally.

**Comment by yonghan** [comment]
Thanks!
