### ISSUE TITLE
package for nixpkgs please

### ISSUE THREAD

**Issue by aanderse** [zhaofengli/colmena#41]
`colmena` is my **favourite** deploy tool for NixOS! I would love for it to be packaged in nixpkgs. Any blockers now that there has been a stable release?

**Comment by zhaofengli** [comment]
Sorry, was meaning to do that shortly after release but I forgot. I just submitted NixOS/nixpkgs#148098 :smiley:

**Comment by zhaofengli** [comment]
PR was merged, will update docs and close this after it hits nixos-unstable.

**Comment by zhaofengli** [comment]
Also backported to 21.11 in #149123. Thanks @0x4A6F.
