### ISSUE TITLE
make `colmena apply dry-activate` verbose by default?

### ISSUE THREAD

**Issue by aanderse** [zhaofengli/colmena#44]
From the `nixos-rebuild` manual:

> dry-activate
           Build the new configuration, but instead of activating it, show what changes would be performed by the activation (i.e. by nixos-rebuild test). For instance, this
           command will print which systemd units would be restarted. The list of changes is not guaranteed to be complete.

I'm not sure how much use `dry-activate` is without passing the `--verbose` flag. Maybe `dry-activate` should just always imply `--verbose`?

**Comment by zhaofengli** [comment]
Good point. It's indeed quite useless when you can't see the full output :smile:

**Comment by aanderse** [comment]
Thank you!
