### ISSUE TITLE
apply option to reboot

### ISSUE THREAD

**Issue by lheckemann** [zhaofengli/colmena#46]
Reboots (`switch-to-configuration boot` followed by a reboot) can be desirable for applying major changes such as stdenv rebuilds or kernel updates. Currently, the only way I'm aware of to do this with colmena is to `colmena apply boot` then `colmena exec -- reboot`. This feels a bit unwieldy though, a `reboot` action would be nice to have.

Is there a reason this doesn't already exist which I'm missing?

**Comment by blaggacao** [comment]
```
        "if [ \"$(cat /proc/sys/kernel/osrelease)\" != \"${config.boot.kernelPackages.kernel.version}\" ]; then \
         ${pkgs.systemd}/bin/systemctl kexec \
         || (echo Rebooting instead ... && ${pkgs.systemd}/bin/systemctl reboot) ; fi" \
```

**Comment by otavio** [comment]
It would be great if it could also avoid rebooting if not needed. It could compare the kernel from running system and the activation one and reboot if different.
