### ISSUE TITLE
Cannot deploy to a host without internet

### ISSUE THREAD

**Issue by lheckemann** [zhaofengli/colmena#53]
If for some reason the deployment target doesn't have an internet connection but does have binary caches enabled, copying the system closure will fail rather than falling back to copying directly.

**Comment by zhaofengli** [comment]
There is `--no-substitutes` which disables the use of binary caches when copying to remote nodes. If the flag isn't passed, the default is to add `--use-substitutes` to all `nix-copy-closure` invocations.

We can think about how to improve the UX in this case. Ideally, most of those options should be configurable using the `deployment.*` options and overridable from the CLI, so the user can easily set them on a per-host basis or even dynamically generate them using some other criteria. `deployment.buildOnTarget` (overridable with `--build-on-target` / `--no-build-on-target`) is one example of this, and we should expand it to more options in a cleaner way.

**Comment by lheckemann** [comment]
I suppose nix itself should also fall back to copying locally when the substituters aren't working on the other end.

As for the `--no-substitutes` option, I apparently didn't read the help text closely enough! My use case is addressed perfectly well by that, so I'd be happy to close the issue. We can keep it around if you want to keep it for making this a deployment option though!

(maybe this is better addressed by setting the machine not to have any substituters though)
