### ISSUE TITLE
Colmena build is stuck unless "-v" argument is present

### ISSUE THREAD

**Issue by xddxdd** [zhaofengli/colmena#65]
When I run `colmena build --on some-host`, colmena will be stuck in the "Evaluating" step and seemingly never ends. When I run `colmena build --on some-host -v` (note the added `-v` argument), the same build continues normally and finishes within one minute.

Example output:

```bash

# Time 00:25:20 
$ colmena build --on some-host
warning: Git tree '/path/to/my/nixos-config' is dirty
[INFO ] Using flake: git+file:///path/to/my/nixos-config
[INFO ] Enumerating nodes...
warning: Git tree '/path/to/my/nixos-config' is dirty
warning: Git tree '/path/to/my/nixos-config' is dirty
warning: Git tree '/path/to/my/nixos-config' is dirty
[INFO ] Selected 1 out of 13 hosts.
                🕓 54s 1 running
# I pressed Ctrl-C after ~1min, but it will run forever if I didn't do that

# Time 00:26:19
$ colmena build --on some-host -v
warning: Git tree '/path/to/my/nixos-config' is dirty
[INFO ] Using flake: git+file:///path/to/my/nixos-config
[INFO ] Enumerating nodes...
warning: Git tree '/path/to/my/nixos-config' is dirty
warning: Git tree '/path/to/my/nixos-config' is dirty
warning: Git tree '/path/to/my/nixos-config' is dirty
[INFO ] Selected 1 out of 13 hosts.
some-host | Evaluating some-host
some-host | warning: Git tree '/path/to/my/nixos-config' is dirty
some-host | Evaluated some-host
some-host | Building some-host
some-host | /nix/store/xl1n3k4vbd8aa20kgs6nx10wyyzmbiij-nixos-system-some-host-22.05pre-git
some-host | Built "/nix/store/xl1n3k4vbd8aa20kgs6nx10wyyzmbiij-nixos-system-some-host-22.05pre-git"
          | All done!
# Time 00:26:36, the same job is done in 20 seconds
```

When colmena is stuck, it seems to be waiting for a defunct `nix-store` process:

```bash
$ ps -aux
# ...
lantian   811648  0.1  0.0 1225260 6016 pts/1    S<l+ 00:25   0:00 colmena build --on some-host
lantian   847160  0.0  0.0      0     0 pts/1    Z<+  00:25   0:00 [nix-store] <defunct>
```

Bisect shows this issue is introduced in <https://github.com/zhaofengli/colmena/commit/26b2203da9a8a0f7913c61de3343430da66579b5>.

I'm on latest nixos-unstable, and here's my `nix-info` report:

```bash
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.13-xanmod1-lantian, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220311_d532269`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```

**Comment by zhaofengli** [comment]
Thanks for the report! I just tested, and it did indeed take an abnormally long time for eval to finish (3 minutes in my case) when the spinners are enabled (no `-v`). After updating [indicatif](https://github.com/console-rs/indicatif) from `0.17.0-rc.7` to `0.17.0-rc.9` the issue disappeared for me [1]. Could you confirm whether https://github.com/zhaofengli/colmena/commit/bef34b1e30d81245a5a194beda5c5a95f1e2587b fixes the issue?

It's a bit embarrassing that I somehow missed such breakage in core functionality for 10 days. I usually leave Colmena running in the background when doing large deployments and use `-v` when testing, which was probably why I didn't notice the issue. Thanks again for noticing this and reporting it!

[1] I haven't bisected, but my theory is that https://github.com/console-rs/indicatif/commit/f81170c8ee240c6b4cc01e2b9a72b8bb45f5a721 fixed the problem in indicatif.

**Comment by xddxdd** [comment]
Yes, the problem is fixed with the latest commit. Thanks for your help!
