### ISSUE TITLE
Raw IPv6 addresses in targetHost don't seem to be handled properly

### ISSUE THREAD

**Issue by CitadelCore** [zhaofengli/colmena#7]
```
[ERROR] Deployment to <redacted> failed. Last 5 lines of logs:
[ERROR] sh: -c: option requires an argument
[ERROR] sh: -c: option requires an argument
[ERROR] error: --- Error --- nix-copy-closure
[ERROR] don't know how to open Nix store 'ssh://root@2a10:4a80:407:3:f816:3eff:fe68:e112?compress=true'
[ERROR]
```

Seems like nix-copy-closure might want this in a different format?

**Comment by zhaofengli** [comment]
Yes, this is expected if you use `nixUnstable`, which is why I'm using the stable Nix now (I use IPv6 literals as the `targetHost` as well) :stuck_out_tongue:

See nixos/nix#4319 (fixed in master but not released).

**Comment by CitadelCore** [comment]
Aha, will close this then seeing as it's an unrelated issue.
