### ISSUE TITLE
Warning when using latest nixos-unstable

### ISSUE THREAD

**Issue by JCapucho** [zhaofengli/colmena#74]
Running `colmena` with a node using `nixpkgs` at `b6966d9` produces the following warning

```
warning: The following Nixpkgs configuration keys set in meta.nixpkgs will be ignored: allowAliases
```

This seems to be because https://github.com/NixOS/nixpkgs/pull/166792 introduced a new config key.

This doesn't seem harmful but I don't fully understand the consequences of it.

**Comment by zhaofengli** [comment]
Thanks for the report! This warning is intended for the untyped config keys (e.g., allowUnfree) which cannot be merged through the module system. I've added it to the list of exceptions so the warning does not appear. In the future, the warning may be removed altogether when all config keys become typed.
