### ISSUE TITLE
deployment.keys.<key>.keyFile appears to not work

### ISSUE THREAD

**Issue by dminuoso** [zhaofengli/colmena#78]
Given this directory structure
```
- profiles/base.nix
- profiles/secret
- flake.nix
```

And `base.nix` has `deployment.keys.secret.keyFile = ./secret`, this will produce `Failed to upload keys: I/O Error: No such file or directory (os error 2)` errors. 

Would I be doing something obviously wrong here?

**Comment by dminuoso** [comment]
Ohh wow. Just as I send created this issue, it hit me.

First I thought it was revolving relative to the top level directory for some erroneous project.

When using flakes, it is required that all files be checked into the repository, unless we refer to the flake via path: or maybe --impure.

A better solution is to simply use sops-nix.

**Comment by mcncm** [comment]
My apologies for re-opening this issue, but I'm very curious what the recommended approach is now. It's really not obvious--at least from the documentation--how to get `keyFile` to work in a flake. It doesn't appear to work even when passing `--impure`! Since flakes-compatibility and secrets management are two of the major selling points for colmena, it's unfortunate they seem to be at odds with one another. Could this issue, and its best-practices workarounds, be clarified somehow in the documentation? I really like the tool, and if there's a way to get around this problem without adding another dependency, it would be nearly perfect!

**Comment by zhaofengli** [comment]
You need to check it into the repository with `git add ./secret.key` for example. The big downside is that the secret will be stored in the Nix store of the machine running Colmena, since Nix copies the entire flake into the store during evaluation.

**Comment by mcncm** [comment]
Hi Zhaofeng, thank you for the very quick reply. I see, that makes sense. It's too bad that that's the only way... Well, I won't trouble you with drive-by feature requests, but _if_ a workaround ever comes up, it would be a fantastic capability for the tool to have. Thank you for all your hard work on this project!

**Comment by otavio** [comment]
Using `sops-nix` solves it.

**Comment by spinus** [comment]
> The big downside is that the secret will be stored in the Nix store of the machine running Colmena, since Nix copies the entire flake into the store during evaluation.

That sounds like undesirable security issue and this is not even mentioned in the documentation. Please be more explicit or maybe consider removing this. It may create non-obvious security holes (for example if someone is deploying from CI host where other processes may access /nix)

**Comment by dminuoso** [comment]
@spinus 
This is just a core behavior with nix.

Like pointed out earlier, using sops-nix addressed this well enough. It is what we use for all NixOS machines company wide. This has the added benefit that the repository is going to be enough for manage a machine, without requiring local state to be present.

**Comment by jess-sch** [comment]
In case anyone in the future comes across this: Another option is to set  `keyCommand = [ "cat" ".secrets/mysecret" ];` because the keyCommand is executed outside of the nix build process.
