### ISSUE TITLE
KeySource does not deserialize

### ISSUE THREAD

**Issue by justinas** [zhaofengli/colmena#8]
With the following hive definition:

```nix
{
  alpha = { pkgs, ... }: {
    deployment.targetHost = "";
    deployment.keys.textual = {
      text = "textual_content";
    };

    imports = [ <...> ];
  };
}
```

Colmena panics with:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected a sequence", line: 1, column: 188)', src/nix/hive.rs:55:52
```

The problem seems to be with the new [KeySource enum](https://github.com/zhaofengli/colmena/blob/2886662e18e5500e032003745c4cf38ed4c2771d/src/nix/key.rs#L16-L26). Nix JSON output contains explicit `null` values for unset options:

```json
{
  "alpha": {
    "textual": {
      "destDir": "/run/keys",
      "group": "root",
      "keyCommand": null,
      "keyFile": null,
      "permissions": "0600",
      "text": "textual_content",
      "user": "root"
    }
  }
}
```

Serde seems to prefer the first variant alphabetically in the source code, in this case, `KeySource::Command`. Since the JSON object contains a key for it, it decides that this is the variant to be deserialized. However, it then fails as the type does not match. Such thing presumably does not happen if the field is omitted altogether, rather than explicitly set to null.

I have tried various `#[serde(untagged)]`, `#[serde(flatten)]`, etc. combinations, but could not arrive to a solution, without writing something like a custom serializer.

**Comment by zhaofengli** [comment]
Hmm, somehow I didn't encounter that after playing with it for a bit. Well, let's try something else. Just pushed a commit that serializes `KeySource` through an intermediate struct, which should still be cleaner than `if/else`-ing all the way.

Could you try if it works? And yes, we definitely need unit tests, but it's 1am here and I'm sleepy, so I'll leave it for tomorrow :stuck_out_tongue:

**Comment by justinas** [comment]
Seems to work okay as of e49e9367c0a803de3cc5312d85121dce2aabc6d5 (command, file, text).

I believe the error would not occur if one used "keyCommand", as then the first (alphabetically) variant contains a non-null value. Anyways, thanks for the swift fix and sorry for disturbing your sleep :sweat_smile:

**Comment by zhaofengli** [comment]
Nice, thanks for confirming!
