### ISSUE TITLE
Could I get an example of using this with sops-nix?

### ISSUE THREAD

**Issue by dmoonfire** [zhaofengli/colmena#84]
I wanted to use `sops-nix` to check in most of the secrets with the file, however I can't figure out how to get it integrated. I tried following the directions at https://github.com/Mic92/sops-nix for a flake-based setup, but `modules` didn't work and `imports` gave me an infinite recursion. Could I please get a hint of how to get these to integrate? Thank you.

**Comment by zhaofengli** [comment]
The following seems to build for me:

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    sops-nix.url = "github:Mic92/sops-nix";
  };

  outputs = { self, nixpkgs, sops-nix }: {
    colmena = {
      meta = {
        nixpkgs = import nixpkgs {
          system = "x86_64-linux";
          overlays = [];
        };
      };

      defaults = {
        imports = [
          sops-nix.nixosModules.sops
        ];
      };

      alpha = {
        boot.isContainer = true;

        sops.defaultSopsFile = ./secrets.yaml;
        sops.age.keyFile = "/fake";
        sops.secrets.example_key = {
        };
      };
    };
  };
}
```

**Comment by dmoonfire** [comment]
I was missing the defaults.imports line; I tried a lot of other places but apparently not that one.

Thank you.
