### ISSUE TITLE
Per-node `specialArgs`

### ISSUE THREAD

**Issue by fooker** [zhaofengli/colmena#93]
Allow to specify a per-nodes `specialArgs` which is passed in during evaluation.

Alternative approach is to allow a custom evaluation function.

**Comment by fooker** [comment]
As another alternative, It may be possible to copy `specialArgs` from the `nodeNixpkgs` into the evaluation call.

**Comment by ThinkChaos** [comment]
This was fixed by #100 and can be closed.
